// enum 키워드로 "이 중에서만 강아지 종을 고를 수 있다"는 목록을 만듦

package com.tmd.backend.domain.pet;

public enum Breed {
    MALTESE, POODLE, TOY_POODLE, POMERANIAN, CHIHUAHUA,
    BICHON_FRISE, YORKSHIRE_TERRIER, SHIH_TZU, PAPILLON,
    DACHSHUND, PUG, FRENCH_BULLDOG, JACK_RUSSELL_TERRIER,
    WELSH_CORGI, MALTIPOO, MINIATURE_PINSCHER, PEKINGESE,
    SHETLAND_SHEEPDOG, LHASA_APSO, HAVANESE,
    MINIATURE_SCHNAUZER, WEST_HIGHLAND_WHITE_TERRIER,

    SHIBA_INU, JINDO, COCKER_SPANIEL, BEAGLE, BORDER_COLLIE,
    BULLDOG, AMERICAN_BULLY, SAMOYED, SIBERIAN_HUSKY,
    AUSTRALIAN_SHEPHERD, BASSET_HOUND, ENGLISH_COCKER_SPANIEL,
    CHOW_CHOW, DALMATIAN, AKITA_INU, BULL_TERRIER,

    GOLDEN_RETRIEVER, LABRADOR_RETRIEVER, GERMAN_SHEPHERD,
    STANDARD_POODLE, GREAT_PYRENEES, DOBERMAN, ROTTWEILER,
    BOXER, ALASKAN_MALAMUTE, BERNESE_MOUNTAIN_DOG,
    SAINT_BERNARD, GREAT_DANE,

    MIXED, ETC
}
