spring:
  application:
    name: tmd-back-end
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true

server:
  port: 8080
